import type { Metadata } from "next";
import { Flex, Text } from "@chakra-ui/react";
import { DecorCircle } from "@/shared";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Lunza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-screen overflow-x-hidden">
      <header></header>
      <Image
        priority
        src={"/bg-auth-lunza.jpeg"}
        fill
        className="object-cover bg-cover bg-center max-md:hidden!"
        alt="Background-Lunza"
      />
      <main className="flex justify-between flex-grow z-10">
        <Flex
          display={{ base: "none", md: "flex" }}
          gap={"3"}
          flexDirection={"column"}
          justifyContent={"end"}
          basis={"auto"}
          flexGrow={"1"}
          padding={{ base: "20px", md: "28px", lg: "72px" }}
        >
          <Text
            as={"h1"}
            textTransform={"uppercase"}
            fontSize={{ base: "7xl", lg: "8xl", xl: "9xl" }}
            textAlign={"start"}
            fontWeight={"bold"}
            lineHeight={"0.82em"}
            letterSpacing={"0.22em"}
            color={"text.white"}
          >
            Lunza
          </Text>

          <Text
            as={"p"}
            fontSize={{ base: "lg", lg: "2xl", xl: "3xl" }}
            color={"text.white"}
          >
            Общайся. Делись. Вдохновляй.
          </Text>
        </Flex>
        <Flex
          gap={"5"}
          position={"relative"}
          background={"bg.app"}
          basis={{ base: "100%", md: "55%", lg: "48%" }}
          height={"full"}
          roundedLeft={{ base: "none", md: "xl" }}
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          padding={{ base: "3", xs: "5" } as any}
          justifyContent={"center"}
          alignItems={"center"}
          flexDirection={"column"}
          overflowY={"visible"}
        >
          <DecorCircle />
          <Flex
            flex={1}
            justifyContent={"center"}
            alignItems={"center"}
            zIndex={2}
          >
            {children}
          </Flex>

          <Text
            fontSize={"sm"}
            fontWeight={"light"}
            width={"full"}
            textAlign={"center"}
          >
            Bodich © 2025 — LUNZA
          </Text>
        </Flex>
      </main>
      <footer></footer>
    </div>
  );
}
