import { Box, Container } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Toaster, widthContainer } from "@/shared";
import { CreatePostDialog } from "@/features/create-post";
import { Header } from "@/widgets/header";
import { Sidebar } from "@/widgets/sidebar";

export const metadata: Metadata = {
  title: "Lunza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <Sidebar />
      <Toaster />
      <CreatePostDialog />
      <Box
        background={"bg.app"}
        as={"main"}
        className="max-[1530px]:pl-[50px] max-md:pl-[0] min-h-screen"
      >
        <Container maxW={widthContainer} paddingTop={"100px"}>
          {children}
        </Container>
      </Box>
    </>
  );
}
