import { Box, Container } from "@chakra-ui/react";
import { Header, Sidebar } from "@/widgets";
import type { Metadata } from "next";
import { Toaster, widthContainer } from "@/shared";
import { SidebarProvider } from "@/features/toggle-sidebar";

export const metadata: Metadata = {
  title: "Lunza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <Header />
      <Sidebar />
      <Toaster />
      <Box
        background={"backgroundPrimary"}
        as={"main"}
        className="max-[1530px]:pl-[50px] max-md:pl-[0] min-h-screen"
      >
        <Container maxW={widthContainer} paddingTop={"100px"}>
          {children}
        </Container>
      </Box>
    </SidebarProvider>
  );
}
