import { Header } from "@/widgets/header";
import { Container } from "@chakra-ui/react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Lunza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main>
        <Container maxW={"1360px"}>{children}</Container>
      </main>
      <footer>Footer</footer>
    </>
  );
}
